[package]
name = "hcrail-hyprland-util"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
hyprland = "0.4.0-beta.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
